### ISSUE TITLE
Incorrect indexing of Adiff

### ISSUE THREAD

**Issue by lmtsui** [YenTaHuang/TNR_project#5]
this line

https://github.com/YenTaHuang/TNR_project/blob/4cdef4d87c37c9725349d182dd36df385aa047c3/mainScInvTNR.py#L105

should appear after appending A_new to A. It causes incorrect indexing of A_diff and will cause further trouble in calculating scaling dimensions

**Comment by YenTaHuang** [comment]
fixed in the new version
